/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package XML;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author EngComp
 */
public class NewJFrame extends javax.swing.JFrame {

    String add;
    LeitorXmlTemp1 leitor = new LeitorXmlTemp1();
    int inicio;
    int fim;

    FilaComum f1 = new FilaComum();
    String teste = " ";

   public NewJFrame() {
        setExtendedState(MAXIMIZED_BOTH);
        setUndecorated(true);
        Image cursorImage = Toolkit.getDefaultToolkit().getImage("xparent.gif");
        Cursor blankCursor = Toolkit.getDefaultToolkit().createCustomCursor(cursorImage, new Point(0, 0), "");
        setCursor(blankCursor);
        initComponents();
        f1.adicionar();

//        add = leitor.adicionar();
        // String[] UmaUm = new String[add.length()];
//        for (int i = 0; i < add.length(); i++) {
//            UmaUm[i] = String.valueOf(add.charAt(i));
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextExemplo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextExemplo.setFont(new java.awt.Font("Franklin Gothic Book", 1, 48)); // NOI18N
        TextExemplo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextExemplo.setAutoscrolls(true);
        TextExemplo.setDoubleBuffered(true);
        TextExemplo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TextExemplo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 976, 1900, 100));

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("http://img0.cptec.inpe.br/~rgrafico/icones_principais/tempo/maior/c.gif")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });

    }

    class FilaComum {

        int inicio;
        int fim;
        int tamanho;
        int qtdeElementos;
        String filaComum[];

        public FilaComum() {
            add = leitor.adicionar();
            inicio = fim = -1;
            tamanho = add.length();
            filaComum = new String[tamanho];

            qtdeElementos = 0;
        }

        public String primeiro() {
            return filaComum[inicio];
        }

        public boolean estaVazia() {
            if (qtdeElementos == 0) {
                return true;
            }
            return false;
        }

        public boolean estaCheia() {
            if (qtdeElementos == tamanho - 1) {
                return true;
            }
            return false;
        }

        public void adicionar() {
            if (!estaCheia()) {
                if (inicio == -1) {
                    inicio = 0;
                }
//                filaComum[fim] = e;
                for (int i = 0; i < add.length(); i++) {
                    filaComum[i] = String.valueOf(add.charAt(i));
                    fim++;
                    qtdeElementos++;
                }

            }
            new Thread() {
                @Override
                public void run() {
                    f1.remover();
                }
            }.start();

        }

        public void remover() {

            while (!estaVazia()) {

                teste = "";
                for (int i = inicio; i < fim; i++) {

                    teste = teste + filaComum[i];

                }
                inicio++;
                qtdeElementos--;

                
                if(inicio==1){
                    try {
                        TextExemplo.setText("..:: 3D - Soluções Tecnológicas ::..");
                        Thread.currentThread().sleep(5000);
                        TextExemplo.setText("TELEFONE: (53) 32481203 - Pinheiro Machado-RS");
                        Thread.currentThread().sleep(5000);
                        TextExemplo.setText(teste);
                        Thread.currentThread().sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                TextExemplo.setText("");
                TextExemplo.setText(teste);
                try {
                    Thread.currentThread().sleep(150);
                } catch (InterruptedException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (estaVazia()) {
                inicio = 0;
                fim = 0;
                tamanho = 0;
                for (int i = 0; i < add.length(); i++) {
                    filaComum[i] = "";
                }
                new Thread() {
                    @Override
                    public void run() {
                        f1.adicionar();
                    }
                }.start();
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextExemplo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
